FROM ubuntu:20.04

# Configura o frontend do Debian para não interativo
ENV DEBIAN_FRONTEND=noninteractive

# Atualizando o sistema e instalando o tzdata com a configuração do fuso horário
RUN apt-get update && \
    apt-get install -y tzdata && \
    ln -fs /usr/share/zoneinfo/America/Sao_Paulo /etc/localtime && \
    dpkg-reconfigure --frontend noninteractive tzdata

# Atualizando o sistema e instalando pacotes necessários
RUN apt update && apt upgrade -y

# Configurando o debconf para responder automaticamente à instalação do postfix
RUN echo "postfix postfix/mailname string localhost" | debconf-set-selections
RUN echo "postfix postfix/main_mailer_type string 'Internet Site'" | debconf-set-selections   


# Instalando pacotes incluindo postfix sem interação
RUN apt-get install -y postfix dnsutils iputils-ping telnet dovecot-common dovecot-core dovecot-imapd dovecot-pop3d \
    apache2 apache2-utils libapache2-mod-php php php-cli php-curl php-xml php-imap nano net-tools supervisor

# Copiando arquivos de configuração
COPY main.cf /etc/postfix/main.cf
COPY /dovecot/10-mail.conf /etc/dovecot/conf.d/10-mail.conf
COPY /dovecot/20-pop3.conf /etc/dovecot/conf.d/20-pop3.conf
COPY /dovecot/10-master.conf /etc/dovecot/conf.d/10-master.conf
COPY /dovecot/dovecot.conf /etc/dovecot/dovecot.conf   


# Criando diretórios e configurando permissões
RUN mkdir -p /var/www/html/rainloop/data && \
    chmod 755 -R /var/www/html/rainloop && \
    chown -R www-data:www-data /var/www/html/rainloop

# Criando usuários
RUN useradd -c 'paulo' -m -s /bin/false paulo && \
    echo "paulo:123456" | chpasswd && \
    useradd -c 'junior' -m -s /bin/false junior && \
    echo "junior:123456" | chpasswd

# Copiar o arquivo de configuração do supervisor
COPY supervisord.conf /etc/supervisor/supervisord.conf

# Expor as portas necessárias
EXPOSE 25 143 80 110

# Iniciar o Supervisor com o arquivo de configuração correto
CMD ["/usr/bin/supervisord", "-c", "/etc/supervisor/supervisord.conf"]