FROM nginx:latest
#COPY nginx.conf /etc/nginx/nginx.conf
COPY default.conf /etc/nginx/conf.d

#CMD ["mkdir","/etc/nginx/ssl/"]

RUN mkdir /etc/nginx/ssl

COPY nginx-selfsigned.crt /etc/nginx/ssl/

COPY nginx-selfsigned.key /etc/nginx/ssl/

#CMD ["chmod", "+755", "/etc/nginx/ssl/certificado.crt"]

